export const actionTypes = {
    REGISTER_START: "REGISTER_START",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    FETCH_MUTUALFUNDS_DATA_START: "FETCH_MUTUALFUNDS_DATA_START",
    FETCH_MUTUALFUNDS_DATA_SUCCESS: "FETCH_MUTUALFUNDS_DATA_SUCCESS",
    FETCH_MUTUALFUNDS_DATA_FAILURE: "FETCH_MUTUALFUNDS_DATA_FAILURE",
    FETCH_FUND_DETAILS: "FETCH_FUND_DETAILS",
    REMOVE_FUND_DETAILS: "REMOVE_FUND_DETAILS",

}